title: QA Roadmap — Manual · Automation · AI
description: A gamified, open QA curriculum — Manual, Automation, AI, API, Performance & Security. Choose your path, level up with real-world examples. By Arifuzzaman Antor (azantor.xyz)
url: "https://azaworld.github.io"
baseurl: "/qa-roadmap"

plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index

relative_links:
  enabled: true
  collections: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
