#!/usr/bin/env python3
"""Parse the MBSTUPC/tech-companies-in-bangladesh AsciiDoc README into _data/bd_companies.yml.
Usage: python3 scripts/parse_bd_companies.py <input.adoc> <output.yml>"""
import sys, re, datetime

src, out = sys.argv[1], sys.argv[2]
lines = open(src, encoding='utf-8').read().split('\n')
in_tbl = False
cells = []
companies = []

def flush(cells):
    for i in range(0, len(cells) - len(cells) % 5, 5):
        name, loc, tech, web, eng = [c.strip() for c in cells[i:i+5]]
        if not name or name.lower().startswith('company name'):
            continue
        m = re.search(r'(https?://[^\[\]\s]+)', web)
        url = m.group(1) if m else ''
        # normalise team size to a sortable number (max integer found; e.g. "100+"->100, "15-20"->20)
        nums = [int(n) for n in re.findall(r'\d+', eng)]
        engnum = max(nums) if nums else 0
        companies.append({'name': name, 'loc': loc, 'tech': tech, 'url': url, 'eng': eng, 'engnum': engnum})

for ln in lines:
    st = ln.strip()
    if st == '|===':
        if in_tbl:
            flush(cells); cells = []; in_tbl = False
        else:
            in_tbl = True; cells = []
        continue
    if in_tbl:
        if not st:
            continue
        if st.count('|') > 1 and 'Company Name' in st:
            continue
        if st.startswith('|'):
            cells.append(st[1:])
if in_tbl and cells:
    flush(cells)

seen = set(); uniq = []
for c in companies:
    k = c['name'].lower().strip()
    if k in seen:
        continue
    seen.add(k); uniq.append(c)
uniq.sort(key=lambda c: c['name'].lower())

def esc(v):
    return (v or '').replace('\\', ' ').replace('"', "'").replace('\n', ' ').strip()

with open(out, 'w', encoding='utf-8') as f:
    f.write('# Software/tech companies in Bangladesh.\n')
    f.write('# Source: github.com/MBSTUPC/tech-companies-in-bangladesh (community-maintained).\n')
    f.write('# Auto-generated by scripts/parse_bd_companies.py — do not edit by hand.\n')
    f.write('parsed: "%s"\n' % datetime.date.today().isoformat())
    f.write('count: %d\n' % len(uniq))
    f.write('companies:\n')
    for c in uniq:
        f.write('  - name: "%s"\n' % esc(c['name']))
        f.write('    loc: "%s"\n' % esc(c['loc']))
        f.write('    tech: "%s"\n' % esc(c['tech']))
        f.write('    url: "%s"\n' % esc(c['url']))
        f.write('    eng: "%s"\n' % esc(c['eng']))
        f.write('    engnum: %d\n' % c['engnum'])
print('parsed %d companies' % len(uniq))
